name: Docker CI
on: [push]

jobs:
  test-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t my-portfolio:latest .
      - name: Run Smoke Test
        run: |
          docker run -d -p 8080:80 --name test-site my-portfolio:latest
          sleep 5
          curl --silent --fail http://localhost:8080 || exit 1